### ISSUE TITLE
Filename should stay consistent (Local vs S3)

### ISSUE THREAD

**Issue by claudesortwell** [adonisjs/drive#31]
## Prerequisites
`file.fileName` after save or move to disk should keep a consistent name between all drive types. Uploading to a path within local will update the file name to `filename.extension`. Uploading to s3 will result in file name being `path/filename.extension`. Not really a bug just a proposed change. 

## Package version
```
"@adonisjs/core": "^5.4.0",
"@adonisjs/drive-s3": "^1.0.5"
```

## Node.js and npm version
Node 16.4.0
Yarn 3.1.1

## Sample Code
```
async function upload(file: MultipartFileContract) {
  await file.moveToDisk("path");
  console.log(file.fileName);
});
```
Change between s3 and local.

```
S3 file.fileName: 'path/filename.extension'
local file.fileName: 'filename.extension'
```

## BONUS
Will provide a sample repo tomorrow if needed. Willing to do a PR, my idea is that it should either keep the path in the filename for local or strip the path out of filename when saving to S3 (since we already have a filePath on a file). Understandably s3 does not actually have file paths. Open to suggestions and not sure how this behaves on GCS.

**Comment by thetutlage** [comment]
Yes, the file name can be inconsistent across drivers. But the value of the file can be used later to generate the file URL or get its content using `Drive.get` method.

So if we remove the `path` from the s3 fileName, then you will not be able to use just the `filename.extension` to fetch the file URL or get its content.

I think this inconsistency shouldn't be a big deal. Because, as the end of the day you can save the fileName to the database and later use it to fetch the file (no modifications required)

**Comment by claudesortwell** [comment]
Makes sense @thetutlage, thanks for the reply. Im going to close this issue now: :+1:
