### ISSUE TITLE
Add support for Uint8Array in addition to Buffer

### ISSUE THREAD

**Issue by targos** [adonisjs/drive#51]
It might just be a question of updating the TypeScript types. At least the Node.js `fs` APIs support both. I don't know about other drivers.

**Comment by thetutlage** [comment]
I am less familiar with Uint8Array. Can you share when you will use it and does it make sense to convert it to buffer inside s3 or gcs drivers (if they don't support it)?

**Comment by targos** [comment]
Technically, Buffer is built on Uint8Array (`class Buffer extends Uint8Array`). It just adds some utility methods on top of it.
There are many libraries which return binary data as Uint8Array (often to be usable in the browser).
It may make sense to convert internally in the drivers (there is a very fast way to create a Buffer from Uint8Array, without copying the underlying data)

**Comment by thetutlage** [comment]
Added to flydrive. https://flydrive.dev/docs/disk_api#getarraybuffer

**Comment by targos** [comment]
Why is it called `getArrayBuffer` if it doesn't return an `ArrayBuffer`?

**Comment by thetutlage** [comment]
Lol. That slipped through the cracks.

I initially created `getArrayBuffer`, but later decided to mimic Bun's API and instead return a `Uint8Array` and rename the method to `bytes`. https://bun.sh/guides/read-file/uint8array

Do you agree that bytes is a better name and there is no need to have dedicated method for returning `ArrayBuffer`, since you can write `Uint8Array.buffer` to access it?

**Comment by targos** [comment]
Yes, sgtm
